[project]
name = "deepsort-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imgcat>=0.6.0",
    "ipdb>=0.13.13",
    "opencv-python>=4.10.0.84",
    "ultralytics>=8.3.57",
    "yt-dlp>=2024.12.23",
]
